version: '3'

volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 995ce397d5fc7de819176d3c7356c1ef463e0ba4ab8ebb73a26d8fde64f8d7bd76509d33aa49b2221be444261514b5e401ce084ec2940195ec6702c02819e44c
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80