# see example in
#https://editor.swagger.io/
---
openapi: 3.0.1
info:
  title: Environmental Sensing API
  version: v1
paths:
  "/api/v1/devices":
    get:
      summary: Retrives all devices
      tags:
      - "Devices"
      responses:
        '200':
          description: devices  found
          content: {}
  "/api/v1/sensor_types":
    get:
      summary: Retrives all sensor types
      tags:
        - "Sensor types"
      responses:
        '200':
          description: sensor types  found
          content: {}
  "/api/v1/sensors":
    get:
      summary: Retrives all sensors
      tags:
        - "Sensors"
      responses:
        '200':
          description: sensors  found
          content: {}
  "/api/v1/sensor_readings":
    get:
      tags:
      - "Sensor readings"
      summary: "Retrives all sensor_readings"
      description: ""
      operationId: "getAllSensorReadings"
      responses:
        '200':
          description: sensor readings  found
          content: {}
    post:
      tags:
        - "Sensor readings"
      summary: "Add a new reading in the database"
      description: ""
      operationId: "addSensorReading"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Reading that need to be inserted in the database"
          required: true
          schema:
            $ref: "#/definitions/sensor_reading"
      responses:
        "405":
          description: "Invalid input"
definitions:
  sensor_reading:
    type: "object"
    required:
      - "sensor_uuid"
      - "sensor_value"
    properties:
      sensor_uuid:
        type: "string"
        example: "123-123-123-123"
      sensor_value:
        type: "integer"
        format: "int64"

servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
