default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: envsensing
  password: envsensing
  host: localhost
  port: 5432

development:
  <<: *default
  database: envsensing_development

test:
  <<: *default
  database: envsensing_test

production:
  <<: *default
  database: envsensing_production